#!/bin/sh

usage() {
	echo "usage: git mikado parent"
	echo "Takes you to the Mikado goal that the current prereq originated from."
}

cmd_default() {	
	#Before change
	branch_name=`git symbolic-ref HEAD 2>/dev/null`
    currentBranch=${branch_name##refs/heads/}	
    echo $currentBranch
    
    parent=`git config branch.$currentBranch.mikado.parent`

    git add --all
    git commit -m "Moving to parent: $parent"
    
    git checkout $parent
}

cmd_help() {
    echo help
}


