#!/bin/sh

usage() {
	echo "usage: git mikado prereq '<prereq text>' <branch-name>"
	echo ""
}

cmd_default() {
	if [ $# -lt 2 ]; then
		usage
		exit 1
	fi
	
	desc=$2;
	newBranch=$3;
	
	#Before change
	branch_name=`git symbolic-ref HEAD 2>/dev/null`
    currentBranch=${branch_name##refs/heads/}	
    echo $currentBranch
    
    prereqs=`git config branch.$currentBranch.mikado.prereqs`
    
	git config branch.$currentBranch.mikado.prereqs "$prereqs $newBranch"
	git stash save -u -a "stash-in-$currentBranch-before-$newBranch" #one stash per prereq
	
	#Reapply by name
	#git stash apply stash^{/$("stash-before-$currentBranch")}
	#Change
	
	# Should we reset to 
    git checkout -b $newBranch
    git config branch.$newBranch.mikado.starttag "`git log -1 --oneline`" #want the first part only
    git config branch.$newBranch.mikado.nodetext "$desc"
    git config branch.$newBranch.mikado.parents $currentBranch
    git config branch.$newBranch.description "$desc"
}

cmd_help() {
    echo help
}


