#!/bin/sh

usage() {
	echo "usage: git mikado new '<mikado goal text>' <branch-name>"
	echo
}

cmd_default() {
	if [ $# -lt 2 ]; then
		usage
		exit 1
	fi
	
	DESCRIPTION = $2;
	BRANCH_NAME = $3;

    git checkout -b $BRANCH_NAME
    git config branch.$BRANCH_NAME.description "$DESCRIPTION"
}

cmd_help() {
    echo help
}


