#!/bin/sh

./publish
rm -rf build
mkdir build
cd build 

git init .
touch afile; git add --all; git commit -m "First commit"
git mikado new "Mikado goal" goal-branch 
touch goalfile;
git mikado prereq "Prereq 1" prereq1 
touch prereq1file;
# git mikado parent
git checkout goal-branch
git mikado prereq "Prereq 2" prereq2 
touch prereq2file;
git mikado prereq "Prereq 2.1" prereq2-1 
touch prereq21file;
git mikado prereq "Prereq 2.1.1" prereq2-1-1
touch prereq211file;
git log --graph 

